# Copyright 2026 dupeGuru developers
#
# This software is licensed under the "GPLv3" License as described in the "LICENSE" file.

"""Safe, bounded video-fingerprint and similarity primitives."""

from core.video.alignment import align_audio_fingerprints, align_frame_fingerprints
from core.video.analyzer import AnalysisLimits, VideoAnalyzer
from core.video.cache import artifact_from_dict, artifact_from_json, artifact_to_dict, artifact_to_json
from core.video.fingerprint import (
    FramePlanPolicy,
    MetadataCandidatePolicy,
    RelationPolicy,
    build_frame_plan,
    classify_metadata_candidate,
    classify_video_relation,
    evidence_from_exact_proof,
    parse_fpcalc_json,
    phash_gray_frame,
)
from core.video.library import (
    VIDEO_EXTENSIONS,
    VIDEO_LIBRARY_GROUP_SCHEMA,
    VIDEO_LIBRARY_RECORD_SCHEMA,
    VIDEO_LIBRARY_SCAN_SCHEMA,
    VideoLibraryLimits,
    VideoLibraryScanner,
)
from core.video.model import (
    ANALYZER_VERSION,
    ARTIFACT_SCHEMA_VERSION,
    AlignmentState,
    AnalysisIssue,
    AnalysisState,
    AudioFingerprint,
    ByteExactProof,
    CandidateAssessment,
    CandidateKind,
    FrameFingerprint,
    FrameOrigin,
    FramePlan,
    FrameRequest,
    RelationMetric,
    SequenceAlignment,
    SourceSnapshot,
    VideoArtifact,
    VideoMetadata,
    VideoRelation,
    VideoRelationEvidence,
)
from core.video.tools import (
    CommandOutcome,
    CommandRunner,
    CommandState,
    FakeCommandRunner,
    SubprocessCommandRunner,
    ToolCapability,
    ToolName,
    ToolState,
    detect_capabilities,
    parse_ffprobe_json,
)

__all__ = [
    "ANALYZER_VERSION",
    "ARTIFACT_SCHEMA_VERSION",
    "AlignmentState",
    "AnalysisIssue",
    "AnalysisLimits",
    "AnalysisState",
    "AudioFingerprint",
    "ByteExactProof",
    "CandidateAssessment",
    "CandidateKind",
    "CommandOutcome",
    "CommandRunner",
    "CommandState",
    "FakeCommandRunner",
    "FrameFingerprint",
    "FrameOrigin",
    "FramePlan",
    "FramePlanPolicy",
    "FrameRequest",
    "MetadataCandidatePolicy",
    "RelationMetric",
    "RelationPolicy",
    "SequenceAlignment",
    "SourceSnapshot",
    "SubprocessCommandRunner",
    "ToolCapability",
    "ToolName",
    "ToolState",
    "VideoAnalyzer",
    "VideoArtifact",
    "VideoLibraryLimits",
    "VideoLibraryScanner",
    "VideoMetadata",
    "VideoRelation",
    "VideoRelationEvidence",
    "align_audio_fingerprints",
    "align_frame_fingerprints",
    "artifact_from_dict",
    "artifact_from_json",
    "artifact_to_dict",
    "artifact_to_json",
    "build_frame_plan",
    "classify_metadata_candidate",
    "classify_video_relation",
    "detect_capabilities",
    "evidence_from_exact_proof",
    "parse_ffprobe_json",
    "parse_fpcalc_json",
    "phash_gray_frame",
    "VIDEO_EXTENSIONS",
    "VIDEO_LIBRARY_GROUP_SCHEMA",
    "VIDEO_LIBRARY_RECORD_SCHEMA",
    "VIDEO_LIBRARY_SCAN_SCHEMA",
]
