__version__ = "5.1.0"
__appname__ = "dupeGuru Neo"
__organization__ = "AiWithYou"
__application_id__ = "io.github.AiWithYou.dupeguru_neo"
__project_url__ = "https://github.com/AiWithYou/dupeguru_neo"
__issue_url__ = f"{__project_url__}/issues"
